import Head from 'next/head'
import { Inter } from 'next/font/google'
import MenuList from '@/components/Menu components/MenuList'
import MenuNavBar from '@/components/Menu components/MenuNavbar'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Kyoto Hibachi Sushi & Bar</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MenuNavBar></MenuNavBar>
      <MenuList></MenuList>
    </>
  )
}
